### ISSUE TITLE
Symfony 4.2 Deprecations

### ISSUE THREAD

**Issue by angelsk** [ckfinder/ckfinder-symfony-bundle#1]
* A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
* The "CKSource\Bundle\CKFinderBundle\Controller\CKFinderController" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use {@see AbstractController} instead.
* Referencing controllers with CKSourceCKFinderBundle:CKFinder:request is deprecated since Symfony 4.1, use "CKSource\Bundle\CKFinderBundle\Controller\CKFinderController::requestAction" instead.

**Comment by zaak** [comment]
Done by @angelsk in https://github.com/ckfinder/ckfinder-symfony-bundle/pull/2.
