### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by BoShurik** [ckfinder/ckfinder-symfony-bundle#12]
Missed Symfony 5 support

**Comment by treeindark** [comment]
why kix:patch-1 not merged ?

**Comment by zaak** [comment]
Hi @treeindark. Thanks for the reminder, merged it.

**Comment by sasha172017** [comment]
how to install this bundle? composer shows error when install it on Symfony 5

**Comment by escees** [comment]
@zaak Monolog dependency needs to be fixed. SF5 comes with monolog 2.0.2 and this bundle is satisfied maximum by version 1.9.1. Are you able to update it?

**Comment by IndyDevGuy** [comment]
Left PR #16

**Comment by zaak** [comment]
@escees: Fixed by @IndyDevGuy in #16.

**Comment by IndyDevGuy** [comment]
I had a typo in the composer.json. Take a look @ PR #17, should be good to go now.

**Comment by lightcoresystems** [comment]
Hi there ! I got another problem with SF5. Commands now have to return a int value, but command "ckfinder:download" returns null..

Symfony change: https://github.com/symfony/symfony/issues/33747

**Comment by treeindark** [comment]
- integration in Symfony 5 returns error “no container set”
 add in services.yaml :

`
 CKSource\Bundle\CKFinderBundle\Controller\CKFinderController:
        calls:
            - [setContainer, ['@service_container']]
`

Ok but now : 
`

Argument 1 passed to CKSource\CKFinder\ExceptionHandler::onCKFinderError() must be an instance of Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent, instance of Symfony\Component\HttpKernel\Event\ExceptionEvent given, called in D:\Web\Foody_dck\vendor\symfony\event-dispatcher\EventDispatcher.php on line 230

`
migration sf5 ???

**Comment by zaak** [comment]
We have started work on Symfony 5 support. The new version of the bundle should be released in about 2 weeks.

**Comment by zaak** [comment]
Symfony 5 support has been added in `v3.5.1.3`.
