### ISSUE TITLE
Service subscriber error

### ISSUE THREAD

**Issue by lightcoresystems** [ckfinder/ckfinder-symfony-bundle#19]
Hi, I have an error running Ckfinder through CKeditor (Images -> Browse), 

> request.CRITICAL: Uncaught PHP Exception LogicException: ""CKSource\Bundle\CKFinderBundle\Controller\CKFinderController" has no container set, did you forget to define it as a service subscriber?" at /var/www/symfony/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 39 {"exception":"[object] (LogicException(code: 0): \"CKSource\\Bundle\\CKFinderBundle\\Controller\\CKFinderController\" has no container set, did you forget to define it as a service subscriber? at /var/www/symfony/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:39)"} []

I think this is connected with https://symfony.com/doc/current/service_container/service_subscribers_locators.html

Im getting this error on Symfony 5

**Comment by zaak** [comment]
Fixed in https://github.com/ckfinder/ckfinder-symfony-bundle/issues/12.
