### ISSUE TITLE
You have requested a non-existent parameter "kernel.root_dir". 

### ISSUE THREAD

**Issue by Gompali** [ckfinder/ckfinder-symfony-bundle#20]
On Symfony 5.0.7 : composer require ckfinder/ckfinder-symfony-bundle
The command produces the following output.

  - Installing ckfinder/ckfinder-symfony-bundle (3.5.1.2): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
56 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony operations: 1 recipe (45147d2f1aac1a4cec6d2bfcab96e643)
  - Configuring ckfinder/ckfinder-symfony-bundle (>=3.5.1.2): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ParameterBag.php line 98:
!!                                                                                 
!!    You have requested a non-existent parameter "kernel.root_dir". Did you mean  
!!     one of these: "kernel.project_dir", "kernel.cache_dir", "kernel.logs_dir"?  
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.

**Comment by btlam87** [comment]
I also got this error when run: composer require ckfinder/ckfinder-symfony-bundle

**Comment by florent6001** [comment]
Hi all,
same error for me, do i need to create a variable in my parameters.yml ?

**Comment by rogergerecke** [comment]
Hi me to,
its error came from
Tests/DependencyInjection/CKSourceCKFinderExtensionTest.php Line45

kernel.root_dir is depractet in symfony 5

**Comment by rogergerecke** [comment]
Symfony 5
https://github.com/ckfinder/ckfinder-symfony-bundle/issues/12

**Comment by rogergerecke** [comment]
Workaround:
If you run composer require ckfinder/ckfinder-symfony-bundle
Composer have download the Pack,  then go to
vendor/ckfinder/ckfinder-symfony-bundle/Resources/config/ckfinder_config.php

In Line 81:82 cange the dir
```
 'root'         => \Symfony\Component\HttpKernel\Kernel::MAJOR_VERSION >= 4
        ? '%kernel.project_dir%/../public/userfiles'
        : '%kernel.project_dir%/../web/userfiles',
    'chmodFiles'   => 0777,
```
Than run fix it
 composer require ckfinder/ckfinder-symfony-bundle

**Comment by rogergerecke** [comment]
or 
```
$root = '%kernel.root_dir%/../web/userfiles';
if (\Symfony\Component\HttpKernel\Kernel::MAJOR_VERSION >= 4) {
    $root = '%kernel.root_dir%/../public/userfiles';
}
if (\Symfony\Component\HttpKernel\Kernel::MAJOR_VERSION >= 5) {
    $root = '%kernel.project_dir%/../public/userfiles';
}

$config['backends']['default'] = array(
    'name'               => 'default',
    'adapter'            => 'local',
    'baseUrl'            => '/userfiles/',
    'root'               => $root,
    'chmodFiles'         => 0777,
    'chmodFolders'       => 0755,
    'filesystemEncoding' => 'UTF-8',
);
```
