### ISSUE TITLE
MimesTypes and Symfony 5

### ISSUE THREAD

**Issue by arthurpietruch** [ckfinder/ckfinder-symfony-bundle#27]
Hi everyone,

Since I migrated from SF4 to SF5, i can't upload any file because :
```
Attempted to load class "MimeTypes" from namespace "Symfony\Component\Mime".
Did you forget a "use" statement for another namespace?
```
I had to run _composer require symfony/mime_ in my Symfony project, but I think this should be required in the composer.json of the bundle instead.

**Comment by pboko** [comment]
I confirm : the Mime component should be a dependency of your bundle
