### ISSUE TITLE
Fixing PSR-4 autoloading standard?

### ISSUE THREAD

**Issue by itarcontact** [ckfinder/ckfinder-symfony-bundle#29]
Hi,
I've noticed problem with composer `"optimize-autoloader": true,` option.
There are some warnings when composer generates classes.

![image](https://user-images.githubusercontent.com/55651445/113864045-b8776900-97aa-11eb-8525-a985ac3d1d5a.png)

**Comment by itarcontact** [comment]
PR https://github.com/ckfinder/ckfinder-symfony-bundle/pull/30

**Comment by zaak** [comment]
Thank you @itarcontact! Merged.
