### ISSUE TITLE
Problem with integration

### ISSUE THREAD

**Issue by louia** [ckfinder/ckfinder-symfony-bundle#4]
I have trouble with CKeditor and Ckfinder. In your example it work fine !!
my config for CKEditor (fosuser ckeditor) : 
`            
filebrowserBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html'
filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.phpcommand=QuickUpload&type=Files'
filebrowserWindowWidth: '1000'
filebrowserWindowHeight: '700'
`
and i have no route founded when i try to browse a file.
I note the url in pop :
for example : http://127.0.0.1:8000/bundles/cksourceckfinder/ckfinder/ckfinder.html?popup=1&configId=editor1&CKEditor=editor1&CKEditorFuncNum=0&langCode=en-gb

and for me : http://127.0.0.1:8000/bundles/cksourceckfinder/ckfinder/ckfinder.html?CKEditor=form_corpsdetexte&CKEditorFuncNum=1&langCode=fr

and i have this error :
No route found for "GET /bundles/cksourceckfinder/ckfinder/core/connector/php/connector.php" (from "http://127.0.0.1:8000/bundles/cksourceckfinder/ckfinder/ckfinder.html?CKEditor=form_corpsdetexte&CKEditorFuncNum=1&langCode=fr")

**Comment by Clemsx** [comment]
Hello @louia I have the same problem, have you found any solution ?

**Comment by zaak** [comment]
Hi @louia! The `filebrowserUploadUrl` option looks invalid: `/ckfinder/core/connector/php/connector.phpcommand=QuickUpload&type=Files`.
To obtain the CKFinder connector path on Twig level, you can use: `{{ path('ckfinder_connector') }}`. Your CKEditor options could then look like.

```js
{
    filebrowserBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html'
    filebrowserUploadUrl: '{{ path('ckfinder_connector') }}?command=QuickUpload&type=Files' 
    filebrowserWindowWidth: '1000' filebrowserWindowHeight: '700'
}
```

I'm sorry for the late reply! I have just noticed that for some reason I had the notifications from this GH repo disabled.

**Comment by JeamBeamCim** [comment]
i had the same problem. after write the correct path of connector now i have a blank page. and i have an error on the browser debug console:
"Uncaught TypeError: Cannot read property 'tools' of undefined
    at connector?command=QuickUpload:2"
window.parent.CKEDITOR is not defined.

any solution for this problem?

**Comment by JeamBeamCim** [comment]
now debug=true and here is the error.log message:

CKFinder.ERROR: CKSource\CKFinder\Exception\MethodNotAllowedException: CKFinder command QuickUpload expects to be called with POST HTTP request. Actual method: GET

**Comment by zaak** [comment]
Hi @JeamBeamCim. Could you provide more details about your configuration? What is the version of CKEditor you use? How is it set up on the web page?

**Comment by JeamBeamCim** [comment]
Hi @zaak, thanks for your quick reply.
version is 3.  i use it for the ckeditor for content editing in symfony easy admin.
my fos_ck_editor.yaml looks like:
`fos_ck_editor:
  input_sync: true
  default_config: base_config
  configs:
    base_config:
      toolbar: standard
      extraPlugins: ['filebrowser']
      filebrowserBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html'
      filebrowserImageBrowseUrl: '/ckfinder/connector?command=Quickuplad&type=Images&responseType=json'

  base_path: "build/ckeditor"
  js_path:   "build/ckeditor/ckeditor.js"`

**Comment by zaak** [comment]
@JeamBeamCim The `filebrowserImageBrowseUrl` option looks invalid, it should be:  
```yml  
filebrowserImageBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html?type=Images'  
```
  
The URL with `command=QuickUpload` param is supposed to be used with `filebrowserUploadUrl` or `filebrowserImageUploadUrl` options, like:  
  
```yml  
filebrowserUploadUrl: '/ckfinder/connector?command=Quickuplad&type=Files&responseType=json'
filebrowserImageUploadUrl: '/ckfinder/connector?command=Quickuplad&type=Images&responseType=json'
```

**Comment by JeamBeamCim** [comment]
Hi @zaak,
i've changed it. same error:
`CKFinder.ERROR: CKSource\CKFinder\Exception\MethodNotAllowedException: CKFinder command QuickUpload expects to be called with POST HTTP request. Actual method: GET`

**Comment by JeamBeamCim** [comment]
@zaak : my config:
`filebrowserBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html?Type=Files'
      filebrowserImageBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html?Type=Images'
      filebrowserUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Files'
      filebrowserImageUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Images'`
it opens the popup window  and i have the error message
The server returned a "404 Not Found".
because it calls:
`http://mydomain/bundles/cksourceckfinder/ckfinder/core/connector/php/connector.php?command=Init`

if i call the link `http://mydomain/ckfinder/connector?command=Init` everything is fine.

**Comment by JeamBeamCim** [comment]
@zaak : my config:
`filebrowserBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html?Type=Files' filebrowserImageBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html?Type=Images' filebrowserUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Files' filebrowserImageUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Images'`
it opens the popup window and i have the error message
`The server returned a "404 Not Found".`
because it calls:
`http://mydomain/bundles/cksourceckfinder/ckfinder/core/connector/php/connector.php?command=Init`

if i call the link `http://mydomain/ckfinder/connector?command=Init` everything is fine.

**Comment by zaak** [comment]
@JeamBeamCim: Could you please paste here what JavaScript code is used to setup CKEditor (not the yaml config, the JS code produced by `FOSCKEditorBundle` and rendered in HTML)?
Another possibility is caching issue, have you tried removing the cache hard way (`rm -rf var/cache/*`)?

**Comment by JeamBeamCim** [comment]
i think this is it:
`var fos_ckeditor_content_content_text = CKEDITOR.replace("content_content_text", 
{"toolbar":[["Cut","Copy","Paste","PasteText","PasteFromWord","-","Undo","Redo"],["Scayt"],["Link","Unlink","Anchor"],["Image","Table","HorizontalRule","SpecialChar"],["Maximize"],["Source"],"\/",["Bold","Italic","Strike","-","RemoveFormat"],["NumberedList","BulletedList","-","Outdent","Indent","-","Blockquote"],["Styles","Format","About"]],"extraPlugins":["filebrowser"],"filebrowserBrowseUrl":"\/bundles\/cksourceckfinder\/ckfinder\/ckfinder.html?Type=Files&responseType=json","filebrowserImageBrowseUrl":"\/bundles\/cksourceckfinder\/ckfinder\/ckfinder.html?Type=Images&responseType=json","filebrowserUploadUrl":"\/ckfinder\/connector?command=QuickUpload&type=Files&responseType=json","filebrowserImageUploadUrl":"\/ckfinder\/connector?command=QuickUpload&type=Images&responseType=json","language":"de"});
fos_ckeditor_content_content_text.on('change', function() { fos_ckeditor_content_content_text.updateElement(); });`

**Comment by zaak** [comment]
@JeamBeamCim: This is kinda shot in the dark, but could you try to embed the following code on the same page, **before** the above code?

```js
<script type="text/javascript" src="/bundles/cksourceckfinder/ckfinder/ckfinder.js"></script>
<script>CKFinder.config( { connectorPath: '/ckfinder/connector' } );</script>
```

If the above doesn't work, please feel free to contact our [support channel](https://ckeditor.com/contact/) so we can discuss more details.

**Comment by JeamBeamCim** [comment]
@zaak: not working. i will contact your support channel. thank for your help anyway.

**Comment by JeamBeamCim** [comment]
@zaak reinstall solved the problem. thank you again.

**Comment by zaak** [comment]
@JeamBeamCim: Awesome! I'm glad you figured it out :slightly_smiling_face:
