### ISSUE TITLE
Symfony6 support

### ISSUE THREAD

**Issue by mike22** [ckfinder/ckfinder-symfony-bundle#45]
Are there any plans to support Symfony6?
Thank you.

**Comment by Kocal** [comment]
You can try https://github.com/Kocal/ckfinder-symfony-bundle, if you only use local or AWS S3 backends.

**Comment by itarcontact** [comment]
@pwiaderny-cksource are you still supporting this bundle? There are no changes for nearly a year!
It would be nice to remove deprecations for Symfony 5.4 and 6.x.

**Comment by bmlotek** [comment]
Hello, ckfinder/ckfinder-symfony-bundle is released for symfony 6. Enjoy.

https://packagist.org/packages/ckfinder/ckfinder-symfony-bundle

**Comment by Kocal** [comment]
That's really good news, thanks @bmlotek!
