### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by lightcoresystems** [ckfinder/ckfinder-symfony-bundle#5]
Hello
I think there is an error in Resources/config/routing.yml.

There is CKSource\Bundle\CKFinderBundle\Controller::requestAction action path, but there is no class CKSource\Bundle\CKFinderBundle\Controller, there should be CKSource\Bundle\CKFinderBundle\Controller\CKFinderController::requestAction

Im getting error about not existance of controller - this change locally resolved this problem.

Regards

**Comment by Hapanovich** [comment]
Hi
To fix this issue you can replace
```
ckfinder_connector:
    resource: "@CKSourceCKFinderBundle/Resources/config/routing.yml"
    prefix:   /
```
with
```
ckfinder_connector:
  path:     /ckfinder/connector
  defaults: { _controller: CKSource\Bundle\CKFinderBundle\Controller\CKFinderController::requestAction }
```
in your `/config/routes/ckfinder.yaml`

**Comment by zaak** [comment]
Thank you for reporting the issue @lightcoresystems! It has been fixed in https://github.com/ckfinder/ckfinder-symfony-bundle/pull/6. The new version of the package has been released.
