### ISSUE TITLE
Symfony 5.4 support

### ISSUE THREAD

**Issue by eddeh** [ckfinder/ckfinder-symfony-bundle#52]
Hello,

Great work on updating this bundle, but now we can't install the bundle on Symfony 5.4 (LTS version).
This version is going to be supported till end 2025.

Is it too much trouble to add both support 5.4 | ^6.0 to the bundle?

**Comment by eddeh** [comment]
@zaak 
Thanks for the update. Maybe docs can be updated?

Ill close this 'issue'

**Comment by zaak** [comment]
It is mentioned in the first sentence of the README 🙂
