### ISSUE TITLE
Not support symfony 7.0

### ISSUE THREAD

**Issue by TianLiangZhou** [ckfinder/ckfinder-symfony-bundle#57]
Hope to add support for symfony 7.0

**Comment by Sergio-Muriel** [comment]
+1

**Comment by FenixPv** [comment]
+1

**Comment by itarcontact** [comment]
+1

**Comment by thedok02** [comment]
+1

**Comment by bsdrazor** [comment]
**UPD**! 
I've created a repository and a composer package based on this repository. Also applied all of the not merged PR's in this repo. Now the bundle works well on my Symfony **7.1.2** project. Feel free to contribute and posting Issues and PR's.

**Links to repository for symfony 7.x + :**

**GitHub**:  [bsdrazor/ckfinder-symfony-bundle](https://github.com/bsdrazor/ckfinder-symfony-bundle)
**Packagist**: [bsdrazor/ckfinder-symfony-bundle](https://packagist.org/packages/bsdrazor/ckfinder-symfony-bundle)

**USAGE:** 
`
composer require bsdrazor/ckfinder-symfony-bundle
`

**Comment by zaak** [comment]
Support for S7 was added in the latest version.

**Comment by itarcontact** [comment]
Ok.... What about deprecations?
![image](https://github.com/user-attachments/assets/adec7d21-63b1-4a9c-a95f-f68dc32101fd)
![image](https://github.com/user-attachments/assets/81453f11-57e2-4560-b31f-51722e7543c0)
![image](https://github.com/user-attachments/assets/d25ef911-353b-4396-827e-2ff7cdd67043)
